window.EXERCISE_CATALOG = Object.freeze([
  { id: 'sentadilla', category: 'Tren inferior', name: 'Sentadilla', english: 'Squat', level: 'Todos', machine: 'Smith machine', freeWeight: 'Barra / Mancuernas / Peso corporal' },
  { id: 'prensa-piernas', category: 'Tren inferior', name: 'Prensa de Piernas', english: 'Leg Press', level: 'Todos', machine: 'Máquina de prensa', freeWeight: 'No aplica' },
  { id: 'extension-cuadriceps', category: 'Tren inferior', name: 'Extensión de Cuádriceps', english: 'Leg Extension', level: 'Todos', machine: 'Máquina de extensión', freeWeight: 'No aplica (o con banda elástica)' },
  { id: 'curl-isquiotibiales', category: 'Tren inferior', name: 'Curl de Isquiotibiales', english: 'Leg Curl', level: 'Todos', machine: 'Máquina tumbada o sentada', freeWeight: 'No aplica (o con pelota de fitball)' },
  { id: 'zancada-estocada', category: 'Tren inferior', name: 'Zancada / Estocada', english: 'Lunge', level: 'Todos', machine: 'No aplica', freeWeight: 'Mancuernas / Peso corporal' },
  { id: 'peso-muerto-rumano', category: 'Tren inferior', name: 'Peso Muerto Rumano', english: 'Romanian Deadlift (RDL)', level: 'Intermedio/Av', machine: 'No aplica', freeWeight: 'Barra / Mancuernas' },
  { id: 'puente-gluteos', category: 'Tren inferior', name: 'Puente de Glúteos', english: 'Glute Bridge', level: 'Todos', machine: 'No aplica', freeWeight: 'Barra / Mancuernas / Peso corporal' },
  { id: 'sentadilla-bulgara', category: 'Tren inferior', name: 'Sentadilla Búlgara', english: 'Bulgarian Split Squat', level: 'Avanzado', machine: 'No aplica', freeWeight: 'Mancuernas (una pierna elevada)' },
  { id: 'patada-gluteo', category: 'Tren inferior', name: 'Patada de Glúteo', english: 'Glute Kickback', level: 'Todos', machine: 'Máquina de polea', freeWeight: 'Banda elástica / Peso en tobillo' },

  { id: 'press-banca', category: 'Empuje', name: 'Press de Banca', english: 'Bench Press', level: 'Todos', machine: 'Smith machine', freeWeight: 'Barra / Mancuernas' },
  { id: 'press-banca-inclinado', category: 'Empuje', name: 'Press de Banca Inclinado', english: 'Incline Bench Press', level: 'Todos', machine: 'Smith machine', freeWeight: 'Mancuernas (banco inclinado)' },
  { id: 'press-hombros', category: 'Empuje', name: 'Press de Hombros', english: 'Shoulder Press / Military Press', level: 'Intermedio', machine: 'Máquina de press', freeWeight: 'Barra / Mancuernas' },
  { id: 'aperturas-pecho', category: 'Empuje', name: 'Aperturas de Pecho', english: 'Chest Fly', level: 'Todos', machine: 'Máquina de pectorales (pec-deck)', freeWeight: 'Mancuernas en banco plano' },
  { id: 'fondos-paralelas', category: 'Empuje', name: 'Fondos en Paralelas', english: 'Dips', level: 'Intermedio/Av', machine: 'Máquina asistida (con contrapeso)', freeWeight: 'Paralelas fijas / Silla (con peso corporal)' },
  { id: 'flexiones-brazos', category: 'Empuje', name: 'Flexiones de Brazos', english: 'Push-ups', level: 'Todos', machine: 'No aplica', freeWeight: 'Peso corporal (variantes: rodillas, declinadas)' },
  { id: 'elevaciones-laterales', category: 'Empuje', name: 'Elevaciones Laterales', english: 'Lateral Raises', level: 'Todos', machine: 'Máquina de laterales', freeWeight: 'Mancuernas' },
  { id: 'elevaciones-frontales', category: 'Empuje', name: 'Elevaciones Frontales', english: 'Front Raises', level: 'Todos', machine: 'Polea', freeWeight: 'Mancuernas / Disco' },
  { id: 'press-frances', category: 'Empuje', name: 'Press Francés', english: 'Skull Crusher / French Press', level: 'Intermedio', machine: 'No aplica', freeWeight: 'Barra Z / Mancuernas (tríceps)' },

  { id: 'dominadas', category: 'Tirón', name: 'Dominadas', english: 'Pull-ups / Chin-ups', level: 'Intermedio/Av', machine: 'Máquina asistida', freeWeight: 'Barra fija (peso corporal)' },
  { id: 'jalon-pecho', category: 'Tirón', name: 'Jalón al Pecho', english: 'Lat Pulldown', level: 'Todos', machine: 'Polea alta', freeWeight: 'No aplica (o con banda elástica)' },
  { id: 'remo-barra', category: 'Tirón', name: 'Remo con Barra', english: 'Bent-over Row', level: 'Intermedio', machine: 'No aplica', freeWeight: 'Barra / Mancuernas' },
  { id: 'remo-sentado', category: 'Tirón', name: 'Remo Sentado', english: 'Seated Cable Row', level: 'Todos', machine: 'Polea baja', freeWeight: 'Banda elástica anclada' },
  { id: 'peso-muerto-convencional', category: 'Tirón', name: 'Peso Muerto Convencional', english: 'Deadlift', level: 'Avanzado', machine: 'No aplica', freeWeight: 'Barra con discos' },
  { id: 'remo-una-mano', category: 'Tirón', name: 'Remo a una Mano', english: 'One-arm Dumbbell Row', level: 'Intermedio', machine: 'No aplica', freeWeight: 'Mancuerna (apoyado en banco)' },
  { id: 'curl-biceps', category: 'Tirón', name: 'Curl de Bíceps', english: 'Bicep Curl', level: 'Todos', machine: 'Máquina de curl / Polea', freeWeight: 'Barra / Mancuernas' },
  { id: 'curl-martillo', category: 'Tirón', name: 'Curl Martillo', english: 'Hammer Curl', level: 'Todos', machine: 'No aplica', freeWeight: 'Mancuernas (agarre neutro)' },
  { id: 'encogimiento-hombros', category: 'Tirón', name: 'Encogimiento de Hombros', english: 'Shrugs', level: 'Todos', machine: 'Máquina de hombros', freeWeight: 'Barra / Mancuernas (para trapecios)' },
  { id: 'face-pull', category: 'Tirón', name: 'Face Pull', english: 'Face Pull', level: 'Todos', machine: 'Polea alta con cuerda', freeWeight: 'Banda elástica (para manguito rotador)' },

  { id: 'plancha', category: 'Core', name: 'Plancha / Tablón', english: 'Plank', level: 'Todos', machine: 'No aplica', freeWeight: 'Peso corporal' },
  { id: 'crunch', category: 'Core', name: 'Crunch / Encogimiento', english: 'Crunch', level: 'Todos', machine: 'Máquina de crunch', freeWeight: 'Peso corporal / Disco en pecho' },
  { id: 'elevacion-piernas', category: 'Core', name: 'Elevación de Piernas', english: 'Leg Raises', level: 'Intermedio', machine: 'Máquina de colgado (roman chair)', freeWeight: 'Suelo o barra fija' },
  { id: 'russian-twist', category: 'Core', name: 'Russian Twist', english: 'Russian Twist', level: 'Intermedio', machine: 'No aplica', freeWeight: 'Disco / Mancuerna (sentado)' },
  { id: 'plancha-lateral', category: 'Core', name: 'Plancha Lateral', english: 'Side Plank', level: 'Intermedio', machine: 'No aplica', freeWeight: 'Peso corporal' },
  { id: 'ab-wheel', category: 'Core', name: 'Ab Wheel / Rueda', english: 'Ab Wheel Rollout', level: 'Avanzado', machine: 'No aplica', freeWeight: 'Rueda abdominal (o barra con discos)' },
  { id: 'bicicleta', category: 'Core', name: 'Bicicleta', english: 'Bicycle Crunch', level: 'Intermedio', machine: 'No aplica', freeWeight: 'Peso corporal' },
  { id: 'pajaro-perro', category: 'Core', name: 'Pájaro-Perro', english: 'Bird-Dog', level: 'Principiante', machine: 'No aplica', freeWeight: 'Peso corporal (estabilidad lumbar)' },

  { id: 'burpees', category: 'Acondicionamiento', name: 'Burpees', english: 'Burpees', level: 'Intermedio/Av', machine: 'No aplica', freeWeight: 'Peso corporal' },
  { id: 'saltos-caja', category: 'Acondicionamiento', name: 'Saltos de Caja', english: 'Box Jumps', level: 'Avanzado', machine: 'No aplica', freeWeight: 'Cajón / Banco' },
  { id: 'sentadilla-salto', category: 'Acondicionamiento', name: 'Sentadilla con Salto', english: 'Jump Squat', level: 'Intermedio', machine: 'No aplica', freeWeight: 'Peso corporal' },
  { id: 'escalador', category: 'Acondicionamiento', name: 'Escalador / Montañista', english: 'Mountain Climbers', level: 'Intermedio', machine: 'No aplica', freeWeight: 'Peso corporal' },
  { id: 'caminata-granjero', category: 'Acondicionamiento', name: 'Caminata de Granjero', english: "Farmer's Walk", level: 'Todos', machine: 'No aplica', freeWeight: 'Mancuernas pesadas / Kettlebells' },
  { id: 'cuerda-batalla', category: 'Acondicionamiento', name: 'Cuerda de Batalla', english: 'Battle Ropes', level: 'Intermedio', machine: 'Máquina de cuerdas', freeWeight: 'No aplica' }
]);
